### ISSUE TITLE
Dotmap Is Missing Data

### ISSUE THREAD

**Issue by iandees** [openaddresses/machine#434] opened 2016-11-09 17:54 UTC
Over in https://github.com/openaddresses/openaddresses/issues/2123, @nvkelso noticed that the dotmap on openaddresses.io doesn't have some of the data that we have in our output. Let's track down where in the chain that data is getting missed and fix it.

**Comment by migurski** [comment] 2016-11-09 18:25
I suspect what's happening is that the dotmap is out of date: the runs have been going over time lately, and I've only got it scheduled on a five day cycle. It might be as much as two weeks out of date, and would not display new sources we have added in that time.

Does that explain what we are seeing?

**Comment by nvkelso** [comment] 2016-11-09 19:05
Looks like @trescube added both of these sources 23 days ago:

- https://github.com/openaddresses/openaddresses/commits/master/sources/us/or/josephine.json
- https://github.com/openaddresses/openaddresses/commits/master/sources/us/or/klamath.json

PR was merged same day: 

- https://github.com/openaddresses/openaddresses/pull/2067

Has the machine not successfully run in the last 23 days?

**Comment by migurski** [comment] 2016-11-10 01:24
Machine is running fine, it’s the separate dotmap process that’s been having difficulties, since it’s been taking more time and running out the clock.

**Comment by migurski** [comment] 2016-11-10 01:30
Looking into those two sources, I see that Klamath [ran on 10/21](https://results.openaddresses.io/sets/119818/) but [failed 10/30](https://results.openaddresses.io/sets/121594/) due to https://github.com/openaddresses/machine/issues/428, while Josephine [ran fine on 11/5](https://results.openaddresses.io/sets/123450/).

Looks like the dotmap is “processing”, which might be a question for @ingalls or @sbma44:

<img width="468" alt="screen shot 2016-11-09 at 8 29 43 pm" src="https://cloud.githubusercontent.com/assets/58730/20161283/491d6be8-a6bb-11e6-8651-0a264678abf5.png">

**Comment by migurski** [comment] 2016-11-12 19:21
Dotmap is still unhappy after the latest run.

**Comment by sbma44** [comment] 2016-11-14 23:54
Sorry to be late to this. I'll try to pull logs and see what's happening. My money's on invalid geometry somewhere.

**Comment by migurski** [comment] 2016-11-15 00:19
Thanks @sbma44!

**Comment by sbma44** [comment] 2016-11-15 02:36
@migurski do you have a specific timestamp of when an upload was attempted? (or better still, completed)

**Comment by migurski** [comment] 2016-11-15 02:38
I don't, unless I can find it out from the spinner UI?

**Comment by sbma44** [comment] 2016-11-15 02:40
no, I don't think there's anything in the studio UI. I was thinking something on the machine box logs.

**Comment by migurski** [comment] 2016-11-15 04:56
The last two upload attempts I can find in the logs are from `2016-10-26 17:46:42` and `2016-10-19 06:44:03` (likely UTC).

**Comment by sbma44** [comment] 2016-11-15 23:12
No luck hunting logs, and the one tile still in our cache did not produce any errors. Can you grab the mbtiles file from the next run & stick it somewhere on s3 where I can grab it?

**Comment by migurski** [comment] 2016-11-16 04:44
Sure, I'll do a manual run next time and keep the thing around.

**Comment by migurski** [comment] 2016-11-16 17:28
Here's the current situation, getting a 422 from Mapbox:

```
Sorting 281255766 featureses
Sorting part 129 of 129
281255766 features, 5906371099 bytes of geometry, 1125023064 bytes of metadata
  99.9%  14/8191/8191    
2016-11-16 12:06:22,916    INFO: Uploading oa-gwu072bd.mbtiles to Mapbox open-addresses's open-addresses.lec54np1
2016-11-16 12:06:22,941   DEBUG: GET /uploads/v1/open-addresses/credentials
2016-11-16 12:06:40,748   DEBUG: /tmp/oa-gwu072bd.mbtiles --> d8/_pending/00dem2ki6oz24jb0zortvkvic/open-addresses
2016-11-16 12:07:20,565   DEBUG: POST /uploads/v1/open-addresses '{"url": "https://tilestream-tilesets-production.s3.amazonaws.com/d8/_pending/00dem2ki6oz24jb0zortvkvic/open-addresses", "tileset": "open-addresses.lec54np1"}'
Traceback (most recent call last):
  File "/usr/local/bin/openaddr-update-dotmap", line 9, in <module>
    load_entry_point('OpenAddresses-Machine==3.7.3', 'console_scripts', 'openaddr-update-dotmap')()
  File "/usr/local/lib/python3.4/dist-packages/openaddr/dotmap.py", line 187, in main
    mapbox_upload(mbtiles_filename, args.tileset_id, args.mapbox_user, args.mapbox_key)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/dotmap.py", line 64, in mapbox_upload
    _mapbox_create_upload(url, tileset, username, api_key)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/dotmap.py", line 111, in _mapbox_create_upload
    raise Exception('Not {}'.format(posted.status_code))
Exception: Not 422
2016-11-16 12:07:21,690 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
2016-11-16 12:07:21,707 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2016-11-16 12:07:21,720 - util.py[WARNING]: Running scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Cloud-init v. 0.7.5 finished at Wed, 16 Nov 2016 12:07:21 +0000. Datasource DataSourceEc2.  Up 24885.67 seconds
```

**Comment by migurski** [comment] 2016-11-16 18:37
For the next ~10 hours until the instance auto-euthanizes, the MBTiles file will be gettable here: http://ec2-54-204-133-201.compute-1.amazonaws.com/oa-gwu072bd.mbtiles

**Comment by sbma44** [comment] 2016-11-23 05:20
(sorry for the super-slow responses here; I'm crashing on client work all day every day and will be for the foreseeable future)

A colleague grabbed this mbtiles and it processes correctly. Is it possible that the upload is timing out on the `machine` end?

**Comment by migurski** [comment] 2016-11-23 06:30
It’s not impossible, but the HTTP 422 from Mapbox indicates something else, maybe?

**Comment by nvkelso** [comment] 2016-12-14 06:28
Current status: OpenAddresses upload a new 2.3GB MBTiles file to Mapbox every ~5 days. But it’s getting rejected each time :(

**Comment by sbma44** [comment] 2016-12-14 15:07
I'm sorry for not having more information here, I spent a few hours digging in without getting anywhere. Having a closer look at the mbtiles now.

**Comment by mollymerp** [comment] 2016-12-14 15:44
:wave: hi there - looking into this this morning with our uploads team. hoping we can find the cause and help get this fixed!

**Comment by nvkelso** [comment] 2016-12-14 16:26
Thank you for the updates, I appreciate your time on this!

**Comment by migurski** [comment] 2016-12-14 17:22
Thanks Molly! I can run this process whenever, and I might be able to short-cut the generation part and just attempt to push the MBTiles file.

**Comment by mollymerp** [comment] 2016-12-14 18:35
great sounds good! I confirmed the tileset / data is not the problem bc its working locally with [mbview](https://github.com/mapbox/mbview) and I successfully uploaded it to my account. You can view the data [here]  (https://api.mapbox.com/styles/v1/mollymerp/ciwp9g2kz006h2qnxlmx9b9t7.html?title=true&access_token=pk.eyJ1IjoibW9sbHltZXJwIiwiYSI6ImNpazdqbGtiZTAxbGNocm0ybXJ3MnNzOHAifQ.5_kJrEENbBWtqTZEv7g1-w#2.2/40.251356/-74.223482/0) and I believe in contains the missing data you noticed in openaddresses/openaddresses#2123. 

According to the logs, it did take 40 minutes from the time I sent the POST request to the uploads API to start the processing til the tileset processing was complete. Is it possible that your script is timing out due to that latency?

**Comment by migurski** [comment] 2016-12-14 19:14
That does look like our data! I don't expect our script to be the problem, since the data is so big and we expect latency all over the place. This is the part that waits for the upload to complete: https://github.com/openaddresses/machine/blob/ab0f33a48/openaddr/dotmap.py#L116-L134

We are seeing the HTTP 422 error from `https://api.mapbox.com/uploads/v1/` here: https://github.com/openaddresses/machine/blob/ab0f33a48/openaddr/dotmap.py#L108-L111

**Comment by mollymerp** [comment] 2016-12-14 19:15
Nvm – the latency theory doesn't make sense.

`422` is the error code that is fired when you try to do something outside of the permissions of your account type (Standard, Premium, etc.) and that's being fired so the upload is not even getting started. I think this is in error though bc you're well within the bounds of storage limits for a premium plan. 

@migurski if you can trigger the process to run I can take a deeper dive into the logs.

**Comment by migurski** [comment] 2016-12-14 21:11
I'll get one started ASAP; might take me a few to figure out how to skip the lengthy Tippecanoe process.

**Comment by mollymerp** [comment] 2016-12-14 21:16
Alright – getting closer. I was able to upload the tiles to your account using the studio UI but I'm having issues when using the uploads API (even though I was able to upload it my account with the API). 

Will look out for your upload – if you could let me know when it starts that would be great so I can flag the logs.

**Comment by migurski** [comment] 2016-12-14 21:35
I'll attempt a new upload at the top of the hour!

**Comment by migurski** [comment] 2016-12-14 22:03
Here you go:

```
2016-12-14 22:01:58,010    INFO: Uploading oa-gwu072bd.mbtiles to Mapbox open-addresses's open-addresses.lec54np1
2016-12-14 22:01:58,010   DEBUG: GET /uploads/v1/open-addresses/credentials
2016-12-14 22:01:58,853   DEBUG: oa-gwu072bd.mbtiles --> 53/_pending/57rxjxfyhoy2v500t3hfhpwic/open-addresses
2016-12-14 22:02:36,775   DEBUG: POST /uploads/v1/open-addresses '{"url": "https://tilestream-tilesets-production.s3.amazonaws.com/53/_pending/57rxjxfyhoy2v500t3hfhpwic/open-addresses", "tileset": "open-addresses.lec54np1"}'
Traceback (most recent call last):
  File "/usr/local/bin/openaddr-update-dotmap", line 9, in <module>
    load_entry_point('OpenAddresses-Machine==3.15.3', 'console_scripts', 'openaddr-update-dotmap')()
  File "/home/ubuntu/machine/openaddr/dotmap.py", line 166, in main
    mapbox_upload('oa-gwu072bd.mbtiles', args.tileset_id, args.mapbox_user, args.mapbox_key)
  File "/home/ubuntu/machine/openaddr/dotmap.py", line 64, in mapbox_upload
    _mapbox_create_upload(url, tileset, username, api_key)
  File "/home/ubuntu/machine/openaddr/dotmap.py", line 111, in _mapbox_create_upload
    raise Exception('Not {}'.format(posted.status_code))
Exception: Not 422
```

**Comment by mollymerp** [comment] 2016-12-14 23:58
@migurski thank you! That helped me track it down. This is a problem on our end with the exception logic in the uploads API, but I'm now able to reproduce the error locally so we should be able to get this taken care of soon. I'll let you know when that is live. Would you like me to update the data for that tileset in the meantime?

**Comment by nvkelso** [comment] 2016-12-15 00:34
@mollymerp That's fantastic to hear, thank you!

@migurski and @mollymerp I'm in favor of updating the data for the tiles in the meantime.

**Comment by nvkelso** [comment] 2016-12-15 00:42
I've taken before pictures so we can celebrate with before/after pictures :)

**Comment by nvkelso** [comment] 2016-12-15 00:57
Using the "October" data:

<img width="1391" alt="screen shot 2016-12-14 at 16 41 30" src="https://cloud.githubusercontent.com/assets/853051/21207666/49cc11a6-c21e-11e6-8b8c-acb1d3e1bcd5.png">

<img width="1388" alt="screen shot 2016-12-14 at 16 41 51" src="https://cloud.githubusercontent.com/assets/853051/21207667/49cc99aa-c21e-11e6-9ce2-b9cccf01f4f8.png">

<img width="1394" alt="screen shot 2016-12-14 at 16 42 05" src="https://cloud.githubusercontent.com/assets/853051/21207665/49b4e6ca-c21e-11e6-98ba-bd6838a72bb3.png">

**Comment by migurski** [comment] 2016-12-15 01:00
And that's not even the newest data! Soon there will be more Italy. @mollymerp thank you so much for finding this exception, I hope it wasn't too hard to fine. I'll just keep running this process every five days and I guess eventually it will magically work?

**Comment by mollymerp** [comment] 2016-12-15 01:03
Happy to help! The data is now updated in the tileset, and actually your process should work now so if you want to test it go ahead.

**Comment by migurski** [comment] 2016-12-15 01:04
All right, I’ll kick one off!

**Comment by migurski** [comment] 2016-12-15 01:55
It’ll run overnight. Meanwhile, I am going to close this issue because it sounds we are good to go.

**Closed by migurski** 2016-12-15 01:55 UTC
Labels: in progress

**Comment by nvkelso** [comment] 2016-12-15 05:21
Verified the map shows _some_ recent additions, but not many of them.

@migurski did you pass Molly the older MBTiles file from 28 days ago in https://github.com/openaddresses/machine/issues/434#issuecomment-261032222 earlier today?

In any event I'll check back in the morning for some after photos and a GIF :)

**Comment by migurski** [comment] 2016-12-15 06:05
Yes, the only data @mollymerp had to work with was the cached data from last month linked above. Some time in the next couple days there should be a new one.

**Comment by mollymerp** [comment] 2016-12-15 22:42
yep, the dataset I added was the one linked from 29 days ago. 
@migurski I've been peeping at your logs today too and haven't seen any attempted uploads – did you run into trouble or is it just that long of a process?

**Comment by migurski** [comment] 2016-12-15 22:43
Ah no, I'm just waiting for the next scheduled one to start up. It should happen tomorrow morning.

**Comment by migurski** [comment] 2016-12-16 15:36
It's running now; should finish sometime in the late morning or early afternoon.

**Comment by migurski** [comment] 2016-12-16 19:09
We are good:

<img width="854" alt="screen shot 2016-12-16 at 11 07 09 am" src="https://cloud.githubusercontent.com/assets/58730/21275092/ff0a5b10-c37f-11e6-8657-c98e72455ab5.png">

Thanks again for your help, @mollymerp!

**Comment by mollymerp** [comment] 2016-12-16 19:32
yayyy so glad to hear it!

**Comment by nvkelso** [comment] 2016-12-16 23:49
As promised, GIFs!

_Note: somehow I messed out the pixel density of USA and EU, but WORLD is spot on, oops._

![map_fix_world](https://cloud.githubusercontent.com/assets/853051/21282137/18c5c25c-c3a7-11e6-8217-ebf28bf57877.gif)

![map_fix_usa](https://cloud.githubusercontent.com/assets/853051/21282136/18c484aa-c3a7-11e6-9031-7a2619a98534.gif)

![map_fix_eu](https://cloud.githubusercontent.com/assets/853051/21282135/18ae7246-c3a7-11e6-893e-9cae434339ae.gif)

**Comment by nvkelso** [comment] 2016-12-16 23:50
Thanks again @mollymerp, @sbma44, and @migurski for revitalizing the OpenAddress dot map :)
